Algoritmo "area_do_retangulo"
// Disciplina   : Programação e algoritimos
// Professora   : Cintia Pinho
// Descrição   : calcular a área do retangulo
// Autor(a)    : João Victor Procópio
// Data atual  : 14/03/2021

Var

   base: inteiro
   altura: inteiro
   area: real

Inicio

     escreva("digite a Base")
     leia(base)
     escreva("digite a Altura")
     leia(altura)

        area:= (base * altura)

     escreva("A Área do retangulo é: " , area )

Fimalgoritmo