Algoritmo "area_do_quadrado "
// Disciplina   : Programação e algoritimos
// Professora   : Cintia Pinho
// Descrição   : calcular a área do quadrado
// Autor(a)    : João Victor Procópio
// Data atual  : 14/03/2021

Var

   base: real
   area: real

Inicio

     escreva("digite a base do quadrado")
     leia(base)
     escreva("digite a base do quadrado")
     leia(base)

        area := base * base
     
     escreva("area do quadrado", area, "m²")
     
Fimalgoritmo